version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: messenger_clone_app
        container_name: messenger_clone_app_container
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/default.conf/local.ini
        networks:
            - messenger-clone-network
        ports:
            - "8080:8080"

    nginx:
        image: nginx:alpine
        container_name: messenger_clone_nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/snippets:/etc/nginx/snippets
        networks:
            - messenger-clone-network


    mysql:
        image: mysql:8.0
        container_name: messenger_clone_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - messenger-clone-network
        ports:
            - "3306:3306"

    npm:
        image: node:20.4-alpine
        container_name: messenger_clone_node
        working_dir: /var/www
        ports:
            - "3000:3000"
        volumes:
            - .:/var/www
        command: >
            sh -c "npm install && npm run dev"
        networks:
            - messenger-clone-network

networks:
    messenger-clone-network:

volumes:
    mysql_data:
